<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Magang_siswa_model extends CI_Model
{

    public $table = 'magang_siswa';
    public $id = 'id_magang_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_magang_siswa', $q);
	$this->db->or_like('kd_unit', $q);
	$this->db->or_like('UNITKERJA_SING', $q);
	$this->db->or_like('NIS', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('bidang', $q);
	$this->db->or_like('perusahaan', $q);
	$this->db->or_like('lokasi', $q);
	$this->db->or_like('tgl_mulai', $q);
	$this->db->or_like('tgl_selesai', $q);
	$this->db->or_like('no_sertifikat', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_magang_siswa', $q);
	$this->db->or_like('kd_unit', $q);
	$this->db->or_like('UNITKERJA_SING', $q);
	$this->db->or_like('NIS', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('bidang', $q);
	$this->db->or_like('perusahaan', $q);
	$this->db->or_like('lokasi', $q);
	$this->db->or_like('tgl_mulai', $q);
	$this->db->or_like('tgl_selesai', $q);
	$this->db->or_like('no_sertifikat', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Magang_siswa_model.php */
/* Location: ./application/models/Magang_siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-13 05:14:12 */
/* http://harviacode.com */