<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pendidikan_siswa_model extends CI_Model
{

    public $table = 'pendidikan_siswa';
    public $id = 'id_pendidikan_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pendidikan_siswa', $q);
	$this->db->or_like('kd_unit', $q);
	$this->db->or_like('UNITKERJA_SING', $q);
	$this->db->or_like('NIM', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nama_prodi', $q);
	$this->db->or_like('strata', $q);
	$this->db->or_like('jenis_kelas', $q);
	$this->db->or_like('jenjang_kelas', $q);
	$this->db->or_like('jenis_pembayaran', $q);
	$this->db->or_like('inputer', $q);
	$this->db->or_like('post_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pendidikan_siswa', $q);
	$this->db->or_like('kd_unit', $q);
	$this->db->or_like('UNITKERJA_SING', $q);
	$this->db->or_like('NIM', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nama_prodi', $q);
	$this->db->or_like('strata', $q);
	$this->db->or_like('jenis_kelas', $q);
	$this->db->or_like('jenjang_kelas', $q);
	$this->db->or_like('jenis_pembayaran', $q);
	$this->db->or_like('inputer', $q);
	$this->db->or_like('post_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pendidikan_siswa_model.php */
/* Location: ./application/models/Pendidikan_siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-06 00:16:22 */
/* http://harviacode.com */