<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Serapan_alumni_model extends CI_Model
{

    public $table = 'serapan_alumni';
    public $id = 'id_serapan_alumni';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_serapan_alumni', $q);
	$this->db->or_like('UNITKERJA_SING', $q);
	$this->db->or_like('kd_unit', $q);
	$this->db->or_like('NIM', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tahun_lulus', $q);
	$this->db->or_like('status_serapan', $q);
	$this->db->or_like('nama_perusahaan_universitas', $q);
	$this->db->or_like('lokasi_perusahaan_universitas', $q);
	$this->db->or_like('bidang_perusahaan_prodi', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->or_like('gaji', $q);
	$this->db->or_like('inputer', $q);
	$this->db->or_like('post_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_serapan_alumni', $q);
	$this->db->or_like('UNITKERJA_SING', $q);
	$this->db->or_like('kd_unit', $q);
	$this->db->or_like('NIM', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tahun_lulus', $q);
	$this->db->or_like('status_serapan', $q);
	$this->db->or_like('nama_perusahaan_universitas', $q);
	$this->db->or_like('lokasi_perusahaan_universitas', $q);
	$this->db->or_like('bidang_perusahaan_prodi', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->or_like('gaji', $q);
	$this->db->or_like('inputer', $q);
	$this->db->or_like('post_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Serapan_alumni_model.php */
/* Location: ./application/models/Serapan_alumni_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-05 07:00:18 */
/* http://harviacode.com */